class CfgConstruction {
	Structures[] = {
		{"","Sandbag1_DZ"},
		{"","Wire_cat1"},
		{"ItemTent","TentStorage"},
		{"ItemTentDome","TentStorageDome"},
		{"ItemCamoNetBig","CamoNet_BLUFOR_big_F"},
		{"ItemCamoNet","CamoNet_BLUFOR_F"},
		{"ItemCamoNetOpen","CamoNet_BLUFOR_open_F"},
		{"B_GeneratorPack","Land_Portable_generator_F"},
		//mesa de trabalho
		{"","ViruZ_WorkStand"},
		//Floor
		{"","VIRUZ_WoodRamp_New"},
		{"","BlockConcrete_F"},
		{"","Land_Pier_F"},
		{"","VIRUZ_Woodfloor_New"},
		//stairs
		{"","ViruZ_PierLadder_F"},
		{"","Land_Canal_Wall_Stairs_F"},
		{"","VIRUZ_GH_Stairs_F"},
		{"","VIRUZ_Woodstair_New"},
		//Houses e Barracas
		{"","Land_Slum_House02_F"},
		{"","Land_i_House_Big_01_V1_F"},
		{"","Land_i_House_Big_01_V2_F"},
		{"","Land_i_House_Big_01_V3_F"},
		{"","Land_i_House_Big_02_V2_F"},
		{"","Land_i_House_Big_02_V3_F"},
		{"","Land_i_Shop_02_V1_F"},
		{"","Land_i_House_Small_01_V1_F"},
		{"","Land_i_House_Small_01_V2_F"},
		{"","Land_i_House_Small_01_V3_F"},
		{"","Land_i_House_Small_02_V1_F"},
		{"","Land_i_House_Small_02_V2_F"},
		{"","Land_i_House_Small_02_V3_F"},
		{"","Land_i_House_Small_03_V1_F"},
		{"","Land_i_Shed_Ind_F"},
		{"","Land_Cargo_House_V1_F"},
		{"","Land_Cargo_House_V3_F"},
		{"","Land_Cargo_HQ_V1_F"},
		{"","Land_Cargo_HQ_V2_F"},
		//gates
		{"","VIRUZ_WoodGate_new"},
		{"","VIRUZ_City_Gate_F"},
		{"","VIRUZ_Net_Fence_Gate_F"},
		{"","VIRUZ_WoodDoor_new"},
		{"","VIRUZ_Generic_Garage"},		
		//Walls
		{"","VIRUZ_WoodWindow_new"},
		{"","VIRUZ_WoodWall_New"},
		{"","Land_Canal_WallSmall_10m_F"},
		{"","Land_City2_4m_F"},
		{"","Land_City2_8m_F"},
		{"","Land_Mil_WiredFence_F"},
		{"","Land_SportGround_fence_noLC_F"},
		//internal Suplyes
		{"","Land_BarrelWater_grey_F"},
		{"","Land_BarrelWater_F"},
		{"","MetalBarrel_burning_F"},
		{"","Land_Camping_Light_off_F"},
		{"","Saco_de_Dormir"},
		//holders
		{"","Rack_Madeira"},
		{"","Stante_Madeira"},
		{"","Rack_Ferro"},
		{"","Stante_Ferro"},
		//iluminação
		{"","Land_PortableLight_single_F"},
		//Barricada
		{"","Land_BagFence_Long_F"},
		{"","Land_BagFence_Short_F"},
		{"","Land_BagFence_End_F"},
		{"","Land_BagFence_Round_F"},
		{"","Land_BagFence_Corner_F"},
		{"","Stante_Ferro"},		
		//cosmetics
		{"","Land_CampingChair_V1_F"},
		{"","Land_CampingChair_V2_F"},
		{"","Land_CampingTable_F"},
		{"","Land_CampingTable_small_F"}
	};
	Vehicles[] = {
		{"B_Boat_Transport_01_F_backpack","B_Boat_Transport_01_F"},
		{"O_Boat_Transport_01_F_backpack","O_Boat_Transport_01_F"},
		{"I_Boat_Transport_01_F_backpack","I_Boat_Transport_01_F"},
		{"B_Lifeboat_backpack","B_Lifeboat"},
		{"C_Rubberboat_backpack","C_Rubberboat"}
	};
};