// config_lha.bin - 20:24:26 04/23/11, generated in 0.24 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

#define VSoft		0
#define VArmor		1
#define VAir		2

#define private		0
#define protected		1
#define public		2

#define ReadAndWrite		0
#define ReadAndCreate		1
#define ReadOnly		2
#define ReadOnlyVerified		3

#define EAST 0 // (Russian)

class CfgPatches {
	class viruz_sound {
		units[] = {};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {};
	};
};

#include "CfgSounds.hpp"
#include "CfgMusic.hpp"
#include "CfgSFX.hpp"
#include "CfgVehicles.hpp"