// Generated by unRap v1.06 by Kegetys

class CfgVoice {
	class NoVoice {
		protocol = "RadioProtocolBase";
		variants[] = {1};
		directories[] = {"", ""};
		identityTypes[] = {"Zombie1", "Zombie2","Zombie3","Zombie4"};
	};
};
